server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enableSelfPreservation: false
    eviction-interval-timer-in-ms: 4000

#management:
#  endpoint:
#    shutdown:
#      enabled: false
#  endpoints:
#    web:
#      exposure:
#        include: "*"
